[package]
name = "structs_and_enums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sha2 = "0.10.2"
#hex = "0.4"
bcrypt = "0.13"
rand = "0.8.3"
